FROM registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.0
MAINTAINER WinJayX <WinJayX@Gmail.com>
LABEL description="This is Ingress Nginx Webhook Server Project"
LABEL version="v1.4.0"
USER root
